[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "project"
version = "0.1.0"
description = "A Python project template"
authors = [
    { name="name", email="your.email@example.com" }
]
requires-python = ">=3.12"